export const ASSET_TYPES = ['METER', 'PUMP', 'TANK', 'PIPE', 'VALVE', 'SENSOR'];
export const UNIT_TYPES = ['CUBIC_METERS', 'LITERS', 'GALLONS'];
export const INCIDENT_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
export const INCIDENT_STATUSES = ['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
export const WORK_ORDER_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
export const WORK_ORDER_STATUSES = ['PENDING', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];
export const REFERENCE_TYPES = ['ASSET', 'INCIDENT', 'WORK_ORDER'];
